#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$DATABASE_USERNAME" <<-EOSQL
    CREATE DATABASE $DATABASE_NAME;
    CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
EOSQL