# Generated by Django 5.1.7 on 2025-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_organization_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.ManyToManyField(blank=True, help_text='Country where the scholarship is offered', related_name='scholarship_countries', related_query_name='scholarship_country', to='api.country'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Interests describing the scholarship', related_name='scholarship_interests', related_query_name='scholarship_interest', to='api.interest'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='type',
            field=models.ManyToManyField(blank=True, help_text='Type of the scholarship', related_name='scholarship_types', related_query_name='scholarship_type', to='api.type'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
