# Generated by Django 5.2.3 on 2025-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userdata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, help_text='Descripción personal', max_length=500, null=True),
        ),
    ]
