# Generated by Django 5.2.3 on 2025-06-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
        ('api', '0010_userdata_bio'),
    ]

    operations = [
    ]
